### ISSUE TITLE
Agregar icono en el footer para redireccionar al administrador

### ISSUE THREAD

**Issue by alexisCode50** [AntonyMatus/project_gsl#1]
![image](https://github.com/AntonyMatus/project_gsl/assets/55004811/3ada5700-e522-4bb5-b0fb-85932402d900)

**Comment by AntonyMatus** [comment]
![image](https://github.com/AntonyMatus/project_gsl/assets/75181075/20e907f7-2e39-4aa1-9e1c-c2202d90a5be)
