### ISSUE TITLE
Quitar todo lo refrenete a la pagina de "register" y "forgot password"

### ISSUE THREAD

**Issue by alexisCode50** [AntonyMatus/project_gsl#4]
Path: /register
![register](https://github.com/AntonyMatus/project_gsl/assets/55004811/083efd29-b6f4-450b-83c1-f1027cfc5fdc)

Path: /forgot-password
![forgot-pass](https://github.com/AntonyMatus/project_gsl/assets/55004811/35c49462-45b9-4a41-bb22-fa5f4b94f539)

Las rutas estan en routes/auth.php:
![auth-path](https://github.com/AntonyMatus/project_gsl/assets/55004811/45cda213-612f-472e-b18b-bc0af97e5b6d)

**Comment by AntonyMatus** [comment]
![image](https://github.com/AntonyMatus/project_gsl/assets/75181075/3d11a655-1c9f-4a06-8e95-837c5e452338)
